//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var GroupMemberLogs = newGroupMemberLogsTable("portal", "group_member_logs", "")

type groupMemberLogsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString // UUID v4
	GroupID   mysql.ColumnString
	UserID    mysql.ColumnString
	Action    mysql.ColumnString // Action type
	ActorID   mysql.ColumnString // User who performed the action
	OldRoles  mysql.ColumnString
	NewRoles  mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type GroupMemberLogsTable struct {
	groupMemberLogsTable

	NEW groupMemberLogsTable
}

// AS creates new GroupMemberLogsTable with assigned alias
func (a GroupMemberLogsTable) AS(alias string) *GroupMemberLogsTable {
	return newGroupMemberLogsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupMemberLogsTable with assigned schema name
func (a GroupMemberLogsTable) FromSchema(schemaName string) *GroupMemberLogsTable {
	return newGroupMemberLogsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupMemberLogsTable with assigned table prefix
func (a GroupMemberLogsTable) WithPrefix(prefix string) *GroupMemberLogsTable {
	return newGroupMemberLogsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupMemberLogsTable with assigned table suffix
func (a GroupMemberLogsTable) WithSuffix(suffix string) *GroupMemberLogsTable {
	return newGroupMemberLogsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupMemberLogsTable(schemaName, tableName, alias string) *GroupMemberLogsTable {
	return &GroupMemberLogsTable{
		groupMemberLogsTable: newGroupMemberLogsTableImpl(schemaName, tableName, alias),
		NEW:                  newGroupMemberLogsTableImpl("", "new", ""),
	}
}

func newGroupMemberLogsTableImpl(schemaName, tableName, alias string) groupMemberLogsTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		GroupIDColumn   = mysql.StringColumn("group_id")
		UserIDColumn    = mysql.StringColumn("user_id")
		ActionColumn    = mysql.StringColumn("action")
		ActorIDColumn   = mysql.StringColumn("actor_id")
		OldRolesColumn  = mysql.StringColumn("old_roles")
		NewRolesColumn  = mysql.StringColumn("new_roles")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{IDColumn, GroupIDColumn, UserIDColumn, ActionColumn, ActorIDColumn, OldRolesColumn, NewRolesColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{GroupIDColumn, UserIDColumn, ActionColumn, ActorIDColumn, OldRolesColumn, NewRolesColumn, CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{CreatedAtColumn}
	)

	return groupMemberLogsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		GroupID:   GroupIDColumn,
		UserID:    UserIDColumn,
		Action:    ActionColumn,
		ActorID:   ActorIDColumn,
		OldRoles:  OldRolesColumn,
		NewRoles:  NewRolesColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
