//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var GroupMembers = newGroupMembersTable("portal", "group_members", "")

type groupMembersTable struct {
	mysql.Table

	// Columns
	GroupID  mysql.ColumnString
	UserID   mysql.ColumnString
	Roles    mysql.ColumnString // Member roles within group: ["admin", "owner", "member"]
	JoinedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type GroupMembersTable struct {
	groupMembersTable

	NEW groupMembersTable
}

// AS creates new GroupMembersTable with assigned alias
func (a GroupMembersTable) AS(alias string) *GroupMembersTable {
	return newGroupMembersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupMembersTable with assigned schema name
func (a GroupMembersTable) FromSchema(schemaName string) *GroupMembersTable {
	return newGroupMembersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupMembersTable with assigned table prefix
func (a GroupMembersTable) WithPrefix(prefix string) *GroupMembersTable {
	return newGroupMembersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupMembersTable with assigned table suffix
func (a GroupMembersTable) WithSuffix(suffix string) *GroupMembersTable {
	return newGroupMembersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupMembersTable(schemaName, tableName, alias string) *GroupMembersTable {
	return &GroupMembersTable{
		groupMembersTable: newGroupMembersTableImpl(schemaName, tableName, alias),
		NEW:               newGroupMembersTableImpl("", "new", ""),
	}
}

func newGroupMembersTableImpl(schemaName, tableName, alias string) groupMembersTable {
	var (
		GroupIDColumn  = mysql.StringColumn("group_id")
		UserIDColumn   = mysql.StringColumn("user_id")
		RolesColumn    = mysql.StringColumn("roles")
		JoinedAtColumn = mysql.TimestampColumn("joined_at")
		allColumns     = mysql.ColumnList{GroupIDColumn, UserIDColumn, RolesColumn, JoinedAtColumn}
		mutableColumns = mysql.ColumnList{RolesColumn, JoinedAtColumn}
		defaultColumns = mysql.ColumnList{RolesColumn, JoinedAtColumn}
	)

	return groupMembersTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		GroupID:  GroupIDColumn,
		UserID:   UserIDColumn,
		Roles:    RolesColumn,
		JoinedAt: JoinedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
