//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var GroupKeys = newGroupKeysTable("portal", "group_keys", "")

type groupKeysTable struct {
	mysql.Table

	// Columns
	GroupID      mysql.ColumnString
	UserID       mysql.ColumnString
	KeyID        mysql.ColumnString // UUID v4
	EncryptedKey mysql.ColumnBlob   // Group symmetric key encrypted with user public key
	CreatedAt    mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type GroupKeysTable struct {
	groupKeysTable

	NEW groupKeysTable
}

// AS creates new GroupKeysTable with assigned alias
func (a GroupKeysTable) AS(alias string) *GroupKeysTable {
	return newGroupKeysTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupKeysTable with assigned schema name
func (a GroupKeysTable) FromSchema(schemaName string) *GroupKeysTable {
	return newGroupKeysTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupKeysTable with assigned table prefix
func (a GroupKeysTable) WithPrefix(prefix string) *GroupKeysTable {
	return newGroupKeysTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupKeysTable with assigned table suffix
func (a GroupKeysTable) WithSuffix(suffix string) *GroupKeysTable {
	return newGroupKeysTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupKeysTable(schemaName, tableName, alias string) *GroupKeysTable {
	return &GroupKeysTable{
		groupKeysTable: newGroupKeysTableImpl(schemaName, tableName, alias),
		NEW:            newGroupKeysTableImpl("", "new", ""),
	}
}

func newGroupKeysTableImpl(schemaName, tableName, alias string) groupKeysTable {
	var (
		GroupIDColumn      = mysql.StringColumn("group_id")
		UserIDColumn       = mysql.StringColumn("user_id")
		KeyIDColumn        = mysql.StringColumn("key_id")
		EncryptedKeyColumn = mysql.BlobColumn("encrypted_key")
		CreatedAtColumn    = mysql.TimestampColumn("created_at")
		allColumns         = mysql.ColumnList{GroupIDColumn, UserIDColumn, KeyIDColumn, EncryptedKeyColumn, CreatedAtColumn}
		mutableColumns     = mysql.ColumnList{EncryptedKeyColumn, CreatedAtColumn}
		defaultColumns     = mysql.ColumnList{KeyIDColumn, CreatedAtColumn}
	)

	return groupKeysTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		GroupID:      GroupIDColumn,
		UserID:       UserIDColumn,
		KeyID:        KeyIDColumn,
		EncryptedKey: EncryptedKeyColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
