//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var GroupPermissions = newGroupPermissionsTable("portal", "group_permissions", "")

type groupPermissionsTable struct {
	mysql.Table

	// Columns
	GroupID    mysql.ColumnString
	Permission mysql.ColumnString // Permission: user:read, user:update, invitation:create, etc.
	CreatedAt  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type GroupPermissionsTable struct {
	groupPermissionsTable

	NEW groupPermissionsTable
}

// AS creates new GroupPermissionsTable with assigned alias
func (a GroupPermissionsTable) AS(alias string) *GroupPermissionsTable {
	return newGroupPermissionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupPermissionsTable with assigned schema name
func (a GroupPermissionsTable) FromSchema(schemaName string) *GroupPermissionsTable {
	return newGroupPermissionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupPermissionsTable with assigned table prefix
func (a GroupPermissionsTable) WithPrefix(prefix string) *GroupPermissionsTable {
	return newGroupPermissionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupPermissionsTable with assigned table suffix
func (a GroupPermissionsTable) WithSuffix(suffix string) *GroupPermissionsTable {
	return newGroupPermissionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupPermissionsTable(schemaName, tableName, alias string) *GroupPermissionsTable {
	return &GroupPermissionsTable{
		groupPermissionsTable: newGroupPermissionsTableImpl(schemaName, tableName, alias),
		NEW:                   newGroupPermissionsTableImpl("", "new", ""),
	}
}

func newGroupPermissionsTableImpl(schemaName, tableName, alias string) groupPermissionsTable {
	var (
		GroupIDColumn    = mysql.StringColumn("group_id")
		PermissionColumn = mysql.StringColumn("permission")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		allColumns       = mysql.ColumnList{GroupIDColumn, PermissionColumn, CreatedAtColumn}
		mutableColumns   = mysql.ColumnList{CreatedAtColumn}
		defaultColumns   = mysql.ColumnList{CreatedAtColumn}
	)

	return groupPermissionsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		GroupID:    GroupIDColumn,
		Permission: PermissionColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
