//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Groups = newGroupsTable("portal", "groups", "")

type groupsTable struct {
	mysql.Table

	// Columns
	ID          mysql.ColumnString // UUID v4
	Name        mysql.ColumnString
	Description mysql.ColumnString
	ParentID    mysql.ColumnString // Parent group for hierarchical structure
	CreatedAt   mysql.ColumnTimestamp
	UpdatedAt   mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type GroupsTable struct {
	groupsTable

	NEW groupsTable
}

// AS creates new GroupsTable with assigned alias
func (a GroupsTable) AS(alias string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupsTable with assigned schema name
func (a GroupsTable) FromSchema(schemaName string) *GroupsTable {
	return newGroupsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupsTable with assigned table prefix
func (a GroupsTable) WithPrefix(prefix string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupsTable with assigned table suffix
func (a GroupsTable) WithSuffix(suffix string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupsTable(schemaName, tableName, alias string) *GroupsTable {
	return &GroupsTable{
		groupsTable: newGroupsTableImpl(schemaName, tableName, alias),
		NEW:         newGroupsTableImpl("", "new", ""),
	}
}

func newGroupsTableImpl(schemaName, tableName, alias string) groupsTable {
	var (
		IDColumn          = mysql.StringColumn("id")
		NameColumn        = mysql.StringColumn("name")
		DescriptionColumn = mysql.StringColumn("description")
		ParentIDColumn    = mysql.StringColumn("parent_id")
		CreatedAtColumn   = mysql.TimestampColumn("created_at")
		UpdatedAtColumn   = mysql.TimestampColumn("updated_at")
		allColumns        = mysql.ColumnList{IDColumn, NameColumn, DescriptionColumn, ParentIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = mysql.ColumnList{NameColumn, DescriptionColumn, ParentIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return groupsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		ParentID:    ParentIDColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
