//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Invitations = newInvitationsTable("portal", "invitations", "")

type invitationsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString    // UUID v4
	Code      mysql.ColumnString    // Invitation code (e.g., XXXX-XXXX-XXXX)
	CreatedBy mysql.ColumnString    // User who created this invitation
	UsedBy    mysql.ColumnString    // User who used this invitation
	ExpiresAt mysql.ColumnTimestamp // Expiration time (NULL = never expires)
	UsedAt    mysql.ColumnTimestamp
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type InvitationsTable struct {
	invitationsTable

	NEW invitationsTable
}

// AS creates new InvitationsTable with assigned alias
func (a InvitationsTable) AS(alias string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InvitationsTable with assigned schema name
func (a InvitationsTable) FromSchema(schemaName string) *InvitationsTable {
	return newInvitationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InvitationsTable with assigned table prefix
func (a InvitationsTable) WithPrefix(prefix string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InvitationsTable with assigned table suffix
func (a InvitationsTable) WithSuffix(suffix string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInvitationsTable(schemaName, tableName, alias string) *InvitationsTable {
	return &InvitationsTable{
		invitationsTable: newInvitationsTableImpl(schemaName, tableName, alias),
		NEW:              newInvitationsTableImpl("", "new", ""),
	}
}

func newInvitationsTableImpl(schemaName, tableName, alias string) invitationsTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		CodeColumn      = mysql.StringColumn("code")
		CreatedByColumn = mysql.StringColumn("created_by")
		UsedByColumn    = mysql.StringColumn("used_by")
		ExpiresAtColumn = mysql.TimestampColumn("expires_at")
		UsedAtColumn    = mysql.TimestampColumn("used_at")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{IDColumn, CodeColumn, CreatedByColumn, UsedByColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{CodeColumn, CreatedByColumn, UsedByColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{IDColumn, CreatedAtColumn}
	)

	return invitationsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Code:      CodeColumn,
		CreatedBy: CreatedByColumn,
		UsedBy:    UsedByColumn,
		ExpiresAt: ExpiresAtColumn,
		UsedAt:    UsedAtColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
