//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var MailLogs = newMailLogsTable("portal", "mail_logs", "")

type mailLogsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString // UUID v4
	MailID    mysql.ColumnString
	Status    mysql.ColumnString // Mail delivery status
	Error     mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type MailLogsTable struct {
	mailLogsTable

	NEW mailLogsTable
}

// AS creates new MailLogsTable with assigned alias
func (a MailLogsTable) AS(alias string) *MailLogsTable {
	return newMailLogsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MailLogsTable with assigned schema name
func (a MailLogsTable) FromSchema(schemaName string) *MailLogsTable {
	return newMailLogsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MailLogsTable with assigned table prefix
func (a MailLogsTable) WithPrefix(prefix string) *MailLogsTable {
	return newMailLogsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MailLogsTable with assigned table suffix
func (a MailLogsTable) WithSuffix(suffix string) *MailLogsTable {
	return newMailLogsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMailLogsTable(schemaName, tableName, alias string) *MailLogsTable {
	return &MailLogsTable{
		mailLogsTable: newMailLogsTableImpl(schemaName, tableName, alias),
		NEW:           newMailLogsTableImpl("", "new", ""),
	}
}

func newMailLogsTableImpl(schemaName, tableName, alias string) mailLogsTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		MailIDColumn    = mysql.StringColumn("mail_id")
		StatusColumn    = mysql.StringColumn("status")
		ErrorColumn     = mysql.StringColumn("error")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{IDColumn, MailIDColumn, StatusColumn, ErrorColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{MailIDColumn, StatusColumn, ErrorColumn, CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{IDColumn, CreatedAtColumn}
	)

	return mailLogsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		MailID:    MailIDColumn,
		Status:    StatusColumn,
		Error:     ErrorColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
