//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Mails = newMailsTable("portal", "mails", "")

type mailsTable struct {
	mysql.Table

	// Columns
	ID         mysql.ColumnString // UUID v4
	To         mysql.ColumnString // Recipients (format: @trap_id;@trap_id2)
	Subject    mysql.ColumnString
	Body       mysql.ColumnString
	OperatorID mysql.ColumnString // User who sent this mail
	CreatedAt  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type MailsTable struct {
	mailsTable

	NEW mailsTable
}

// AS creates new MailsTable with assigned alias
func (a MailsTable) AS(alias string) *MailsTable {
	return newMailsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MailsTable with assigned schema name
func (a MailsTable) FromSchema(schemaName string) *MailsTable {
	return newMailsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MailsTable with assigned table prefix
func (a MailsTable) WithPrefix(prefix string) *MailsTable {
	return newMailsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MailsTable with assigned table suffix
func (a MailsTable) WithSuffix(suffix string) *MailsTable {
	return newMailsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMailsTable(schemaName, tableName, alias string) *MailsTable {
	return &MailsTable{
		mailsTable: newMailsTableImpl(schemaName, tableName, alias),
		NEW:        newMailsTableImpl("", "new", ""),
	}
}

func newMailsTableImpl(schemaName, tableName, alias string) mailsTable {
	var (
		IDColumn         = mysql.StringColumn("id")
		ToColumn         = mysql.StringColumn("to")
		SubjectColumn    = mysql.StringColumn("subject")
		BodyColumn       = mysql.StringColumn("body")
		OperatorIDColumn = mysql.StringColumn("operator_id")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		allColumns       = mysql.ColumnList{IDColumn, ToColumn, SubjectColumn, BodyColumn, OperatorIDColumn, CreatedAtColumn}
		mutableColumns   = mysql.ColumnList{ToColumn, SubjectColumn, BodyColumn, OperatorIDColumn, CreatedAtColumn}
		defaultColumns   = mysql.ColumnList{IDColumn, CreatedAtColumn}
	)

	return mailsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		To:         ToColumn,
		Subject:    SubjectColumn,
		Body:       BodyColumn,
		OperatorID: OperatorIDColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
