//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Namecards = newNamecardsTable("portal", "namecards", "")

type namecardsTable struct {
	mysql.Table

	// Columns
	StudentPrefix mysql.ColumnString // Student number prefix (e.g., 15B, 24B)
	Color         mysql.ColumnString // Hex color code

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type NamecardsTable struct {
	namecardsTable

	NEW namecardsTable
}

// AS creates new NamecardsTable with assigned alias
func (a NamecardsTable) AS(alias string) *NamecardsTable {
	return newNamecardsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new NamecardsTable with assigned schema name
func (a NamecardsTable) FromSchema(schemaName string) *NamecardsTable {
	return newNamecardsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new NamecardsTable with assigned table prefix
func (a NamecardsTable) WithPrefix(prefix string) *NamecardsTable {
	return newNamecardsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new NamecardsTable with assigned table suffix
func (a NamecardsTable) WithSuffix(suffix string) *NamecardsTable {
	return newNamecardsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newNamecardsTable(schemaName, tableName, alias string) *NamecardsTable {
	return &NamecardsTable{
		namecardsTable: newNamecardsTableImpl(schemaName, tableName, alias),
		NEW:            newNamecardsTableImpl("", "new", ""),
	}
}

func newNamecardsTableImpl(schemaName, tableName, alias string) namecardsTable {
	var (
		StudentPrefixColumn = mysql.StringColumn("student_prefix")
		ColorColumn         = mysql.StringColumn("color")
		allColumns          = mysql.ColumnList{StudentPrefixColumn, ColorColumn}
		mutableColumns      = mysql.ColumnList{ColorColumn}
		defaultColumns      = mysql.ColumnList{}
	)

	return namecardsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		StudentPrefix: StudentPrefixColumn,
		Color:         ColorColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
