//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Secrets = newSecretsTable("portal", "secrets", "")

type secretsTable struct {
	mysql.Table

	// Columns
	ID             mysql.ColumnString // UUID v4
	GroupID        mysql.ColumnString // Owning group
	Name           mysql.ColumnString
	EncryptedValue mysql.ColumnBlob // AES-GCM encrypted with group key
	CreatedBy      mysql.ColumnString
	CreatedAt      mysql.ColumnTimestamp
	UpdatedAt      mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type SecretsTable struct {
	secretsTable

	NEW secretsTable
}

// AS creates new SecretsTable with assigned alias
func (a SecretsTable) AS(alias string) *SecretsTable {
	return newSecretsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SecretsTable with assigned schema name
func (a SecretsTable) FromSchema(schemaName string) *SecretsTable {
	return newSecretsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SecretsTable with assigned table prefix
func (a SecretsTable) WithPrefix(prefix string) *SecretsTable {
	return newSecretsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SecretsTable with assigned table suffix
func (a SecretsTable) WithSuffix(suffix string) *SecretsTable {
	return newSecretsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSecretsTable(schemaName, tableName, alias string) *SecretsTable {
	return &SecretsTable{
		secretsTable: newSecretsTableImpl(schemaName, tableName, alias),
		NEW:          newSecretsTableImpl("", "new", ""),
	}
}

func newSecretsTableImpl(schemaName, tableName, alias string) secretsTable {
	var (
		IDColumn             = mysql.StringColumn("id")
		GroupIDColumn        = mysql.StringColumn("group_id")
		NameColumn           = mysql.StringColumn("name")
		EncryptedValueColumn = mysql.BlobColumn("encrypted_value")
		CreatedByColumn      = mysql.StringColumn("created_by")
		CreatedAtColumn      = mysql.TimestampColumn("created_at")
		UpdatedAtColumn      = mysql.TimestampColumn("updated_at")
		allColumns           = mysql.ColumnList{IDColumn, GroupIDColumn, NameColumn, EncryptedValueColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = mysql.ColumnList{GroupIDColumn, NameColumn, EncryptedValueColumn, CreatedByColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return secretsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		GroupID:        GroupIDColumn,
		Name:           NameColumn,
		EncryptedValue: EncryptedValueColumn,
		CreatedBy:      CreatedByColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
