//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SecretLogs = newSecretLogsTable("portal", "secret_logs", "")

type secretLogsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString // UUID v4
	SecretID  mysql.ColumnString
	Action    mysql.ColumnString // Action type
	ActorID   mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type SecretLogsTable struct {
	secretLogsTable

	NEW secretLogsTable
}

// AS creates new SecretLogsTable with assigned alias
func (a SecretLogsTable) AS(alias string) *SecretLogsTable {
	return newSecretLogsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SecretLogsTable with assigned schema name
func (a SecretLogsTable) FromSchema(schemaName string) *SecretLogsTable {
	return newSecretLogsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SecretLogsTable with assigned table prefix
func (a SecretLogsTable) WithPrefix(prefix string) *SecretLogsTable {
	return newSecretLogsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SecretLogsTable with assigned table suffix
func (a SecretLogsTable) WithSuffix(suffix string) *SecretLogsTable {
	return newSecretLogsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSecretLogsTable(schemaName, tableName, alias string) *SecretLogsTable {
	return &SecretLogsTable{
		secretLogsTable: newSecretLogsTableImpl(schemaName, tableName, alias),
		NEW:             newSecretLogsTableImpl("", "new", ""),
	}
}

func newSecretLogsTableImpl(schemaName, tableName, alias string) secretLogsTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		SecretIDColumn  = mysql.StringColumn("secret_id")
		ActionColumn    = mysql.StringColumn("action")
		ActorIDColumn   = mysql.StringColumn("actor_id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{IDColumn, SecretIDColumn, ActionColumn, ActorIDColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{SecretIDColumn, ActionColumn, ActorIDColumn, CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{IDColumn, CreatedAtColumn}
	)

	return secretLogsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		SecretID:  SecretIDColumn,
		Action:    ActionColumn,
		ActorID:   ActorIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
