//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Groups = Groups.FromSchema(schema)
	GroupKeys = GroupKeys.FromSchema(schema)
	GroupMembers = GroupMembers.FromSchema(schema)
	GroupMemberLogs = GroupMemberLogs.FromSchema(schema)
	GroupPermissions = GroupPermissions.FromSchema(schema)
	Invitations = Invitations.FromSchema(schema)
	Mails = Mails.FromSchema(schema)
	MailLogs = MailLogs.FromSchema(schema)
	Namecards = Namecards.FromSchema(schema)
	Secrets = Secrets.FromSchema(schema)
	SecretLogs = SecretLogs.FromSchema(schema)
	Users = Users.FromSchema(schema)
	UserKeys = UserKeys.FromSchema(schema)
	UserLinks = UserLinks.FromSchema(schema)
	UserStatuses = UserStatuses.FromSchema(schema)
	Webhooks = Webhooks.FromSchema(schema)
	WebhookSubscribeEvents = WebhookSubscribeEvents.FromSchema(schema)
}
