//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Users = newUsersTable("portal", "users", "")

type usersTable struct {
	mysql.Table

	// Columns
	ID            mysql.ColumnString // UUID v4
	TrapID        mysql.ColumnString // traP ID (unique username)
	PasswordHash  mysql.ColumnString // PBKDF2-SHA512 hash
	Email         mysql.ColumnBlob   // AES-GCM encrypted email
	PersonalInfo  mysql.ColumnBlob   // AES-GCM encrypted JSON (name, phone, address, etc.)
	StudentNumber mysql.ColumnString // Student number (plaintext for lookup)
	CreatedAt     mysql.ColumnTimestamp
	UpdatedAt     mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type UsersTable struct {
	usersTable

	NEW usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		NEW:        newUsersTableImpl("", "new", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn            = mysql.StringColumn("id")
		TrapIDColumn        = mysql.StringColumn("trap_id")
		PasswordHashColumn  = mysql.StringColumn("password_hash")
		EmailColumn         = mysql.BlobColumn("email")
		PersonalInfoColumn  = mysql.BlobColumn("personal_info")
		StudentNumberColumn = mysql.StringColumn("student_number")
		CreatedAtColumn     = mysql.TimestampColumn("created_at")
		UpdatedAtColumn     = mysql.TimestampColumn("updated_at")
		allColumns          = mysql.ColumnList{IDColumn, TrapIDColumn, PasswordHashColumn, EmailColumn, PersonalInfoColumn, StudentNumberColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = mysql.ColumnList{TrapIDColumn, PasswordHashColumn, EmailColumn, PersonalInfoColumn, StudentNumberColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return usersTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		TrapID:        TrapIDColumn,
		PasswordHash:  PasswordHashColumn,
		Email:         EmailColumn,
		PersonalInfo:  PersonalInfoColumn,
		StudentNumber: StudentNumberColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
