//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var UserLinks = newUserLinksTable("portal", "user_links", "")

type userLinksTable struct {
	mysql.Table

	// Columns
	UserID      mysql.ColumnString
	Service     mysql.ColumnString // Service name
	ExternalID  mysql.ColumnString // External service user ID
	AccountName mysql.ColumnString // Display name/handle on the service
	AccessToken mysql.ColumnBlob   // Encrypted OAuth access token (if stored)
	CreatedAt   mysql.ColumnTimestamp
	UpdatedAt   mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type UserLinksTable struct {
	userLinksTable

	NEW userLinksTable
}

// AS creates new UserLinksTable with assigned alias
func (a UserLinksTable) AS(alias string) *UserLinksTable {
	return newUserLinksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserLinksTable with assigned schema name
func (a UserLinksTable) FromSchema(schemaName string) *UserLinksTable {
	return newUserLinksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserLinksTable with assigned table prefix
func (a UserLinksTable) WithPrefix(prefix string) *UserLinksTable {
	return newUserLinksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserLinksTable with assigned table suffix
func (a UserLinksTable) WithSuffix(suffix string) *UserLinksTable {
	return newUserLinksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserLinksTable(schemaName, tableName, alias string) *UserLinksTable {
	return &UserLinksTable{
		userLinksTable: newUserLinksTableImpl(schemaName, tableName, alias),
		NEW:            newUserLinksTableImpl("", "new", ""),
	}
}

func newUserLinksTableImpl(schemaName, tableName, alias string) userLinksTable {
	var (
		UserIDColumn      = mysql.StringColumn("user_id")
		ServiceColumn     = mysql.StringColumn("service")
		ExternalIDColumn  = mysql.StringColumn("external_id")
		AccountNameColumn = mysql.StringColumn("account_name")
		AccessTokenColumn = mysql.BlobColumn("access_token")
		CreatedAtColumn   = mysql.TimestampColumn("created_at")
		UpdatedAtColumn   = mysql.TimestampColumn("updated_at")
		allColumns        = mysql.ColumnList{UserIDColumn, ServiceColumn, ExternalIDColumn, AccountNameColumn, AccessTokenColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = mysql.ColumnList{ExternalIDColumn, AccountNameColumn, AccessTokenColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return userLinksTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:      UserIDColumn,
		Service:     ServiceColumn,
		ExternalID:  ExternalIDColumn,
		AccountName: AccountNameColumn,
		AccessToken: AccessTokenColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
