//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var UserStatuses = newUserStatusesTable("portal", "user_statuses", "")

type userStatusesTable struct {
	mysql.Table

	// Columns
	UserID    mysql.ColumnString
	Status    mysql.ColumnString // Status type
	Detail    mysql.ColumnString // Additional detail/reason
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type UserStatusesTable struct {
	userStatusesTable

	NEW userStatusesTable
}

// AS creates new UserStatusesTable with assigned alias
func (a UserStatusesTable) AS(alias string) *UserStatusesTable {
	return newUserStatusesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserStatusesTable with assigned schema name
func (a UserStatusesTable) FromSchema(schemaName string) *UserStatusesTable {
	return newUserStatusesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserStatusesTable with assigned table prefix
func (a UserStatusesTable) WithPrefix(prefix string) *UserStatusesTable {
	return newUserStatusesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserStatusesTable with assigned table suffix
func (a UserStatusesTable) WithSuffix(suffix string) *UserStatusesTable {
	return newUserStatusesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserStatusesTable(schemaName, tableName, alias string) *UserStatusesTable {
	return &UserStatusesTable{
		userStatusesTable: newUserStatusesTableImpl(schemaName, tableName, alias),
		NEW:               newUserStatusesTableImpl("", "new", ""),
	}
}

func newUserStatusesTableImpl(schemaName, tableName, alias string) userStatusesTable {
	var (
		UserIDColumn    = mysql.StringColumn("user_id")
		StatusColumn    = mysql.StringColumn("status")
		DetailColumn    = mysql.StringColumn("detail")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{UserIDColumn, StatusColumn, DetailColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{DetailColumn, CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{CreatedAtColumn}
	)

	return userStatusesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		Status:    StatusColumn,
		Detail:    DetailColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
