//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var UserKeys = newUserKeysTable("portal", "user_keys", "")

type userKeysTable struct {
	mysql.Table

	// Columns
	UserID              mysql.ColumnString
	KeyID               mysql.ColumnString // UUID v4
	PublicKey           mysql.ColumnBlob   // User public key (DER format)
	EncryptedPrivateKey mysql.ColumnBlob   // Private key encrypted with user password-derived key
	Algorithm           mysql.ColumnString // Key algorithm
	IsActive            mysql.ColumnBool
	CreatedAt           mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type UserKeysTable struct {
	userKeysTable

	NEW userKeysTable
}

// AS creates new UserKeysTable with assigned alias
func (a UserKeysTable) AS(alias string) *UserKeysTable {
	return newUserKeysTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserKeysTable with assigned schema name
func (a UserKeysTable) FromSchema(schemaName string) *UserKeysTable {
	return newUserKeysTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserKeysTable with assigned table prefix
func (a UserKeysTable) WithPrefix(prefix string) *UserKeysTable {
	return newUserKeysTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserKeysTable with assigned table suffix
func (a UserKeysTable) WithSuffix(suffix string) *UserKeysTable {
	return newUserKeysTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserKeysTable(schemaName, tableName, alias string) *UserKeysTable {
	return &UserKeysTable{
		userKeysTable: newUserKeysTableImpl(schemaName, tableName, alias),
		NEW:           newUserKeysTableImpl("", "new", ""),
	}
}

func newUserKeysTableImpl(schemaName, tableName, alias string) userKeysTable {
	var (
		UserIDColumn              = mysql.StringColumn("user_id")
		KeyIDColumn               = mysql.StringColumn("key_id")
		PublicKeyColumn           = mysql.BlobColumn("public_key")
		EncryptedPrivateKeyColumn = mysql.BlobColumn("encrypted_private_key")
		AlgorithmColumn           = mysql.StringColumn("algorithm")
		IsActiveColumn            = mysql.BoolColumn("is_active")
		CreatedAtColumn           = mysql.TimestampColumn("created_at")
		allColumns                = mysql.ColumnList{UserIDColumn, KeyIDColumn, PublicKeyColumn, EncryptedPrivateKeyColumn, AlgorithmColumn, IsActiveColumn, CreatedAtColumn}
		mutableColumns            = mysql.ColumnList{PublicKeyColumn, EncryptedPrivateKeyColumn, AlgorithmColumn, IsActiveColumn, CreatedAtColumn}
		defaultColumns            = mysql.ColumnList{AlgorithmColumn, IsActiveColumn, CreatedAtColumn}
	)

	return userKeysTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:              UserIDColumn,
		KeyID:               KeyIDColumn,
		PublicKey:           PublicKeyColumn,
		EncryptedPrivateKey: EncryptedPrivateKeyColumn,
		Algorithm:           AlgorithmColumn,
		IsActive:            IsActiveColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
