//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var WebhookSubscribeEvents = newWebhookSubscribeEventsTable("portal", "webhook_subscribe_events", "")

type webhookSubscribeEventsTable struct {
	mysql.Table

	// Columns
	WebhookID mysql.ColumnString
	EventType mysql.ColumnString // Event type: user.created, group.member_added, etc.
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type WebhookSubscribeEventsTable struct {
	webhookSubscribeEventsTable

	NEW webhookSubscribeEventsTable
}

// AS creates new WebhookSubscribeEventsTable with assigned alias
func (a WebhookSubscribeEventsTable) AS(alias string) *WebhookSubscribeEventsTable {
	return newWebhookSubscribeEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WebhookSubscribeEventsTable with assigned schema name
func (a WebhookSubscribeEventsTable) FromSchema(schemaName string) *WebhookSubscribeEventsTable {
	return newWebhookSubscribeEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WebhookSubscribeEventsTable with assigned table prefix
func (a WebhookSubscribeEventsTable) WithPrefix(prefix string) *WebhookSubscribeEventsTable {
	return newWebhookSubscribeEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WebhookSubscribeEventsTable with assigned table suffix
func (a WebhookSubscribeEventsTable) WithSuffix(suffix string) *WebhookSubscribeEventsTable {
	return newWebhookSubscribeEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWebhookSubscribeEventsTable(schemaName, tableName, alias string) *WebhookSubscribeEventsTable {
	return &WebhookSubscribeEventsTable{
		webhookSubscribeEventsTable: newWebhookSubscribeEventsTableImpl(schemaName, tableName, alias),
		NEW:                         newWebhookSubscribeEventsTableImpl("", "new", ""),
	}
}

func newWebhookSubscribeEventsTableImpl(schemaName, tableName, alias string) webhookSubscribeEventsTable {
	var (
		WebhookIDColumn = mysql.StringColumn("webhook_id")
		EventTypeColumn = mysql.StringColumn("event_type")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{WebhookIDColumn, EventTypeColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{CreatedAtColumn}
	)

	return webhookSubscribeEventsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		WebhookID: WebhookIDColumn,
		EventType: EventTypeColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
