//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Webhooks = newWebhooksTable("portal", "webhooks", "")

type webhooksTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString // UUID v4
	Name      mysql.ColumnString
	URL       mysql.ColumnString
	Secret    mysql.ColumnBlob   // HMAC signing secret (encrypted)
	OwnerID   mysql.ColumnString // User who owns this webhook
	IsActive  mysql.ColumnBool
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type WebhooksTable struct {
	webhooksTable

	NEW webhooksTable
}

// AS creates new WebhooksTable with assigned alias
func (a WebhooksTable) AS(alias string) *WebhooksTable {
	return newWebhooksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WebhooksTable with assigned schema name
func (a WebhooksTable) FromSchema(schemaName string) *WebhooksTable {
	return newWebhooksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WebhooksTable with assigned table prefix
func (a WebhooksTable) WithPrefix(prefix string) *WebhooksTable {
	return newWebhooksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WebhooksTable with assigned table suffix
func (a WebhooksTable) WithSuffix(suffix string) *WebhooksTable {
	return newWebhooksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWebhooksTable(schemaName, tableName, alias string) *WebhooksTable {
	return &WebhooksTable{
		webhooksTable: newWebhooksTableImpl(schemaName, tableName, alias),
		NEW:           newWebhooksTableImpl("", "new", ""),
	}
}

func newWebhooksTableImpl(schemaName, tableName, alias string) webhooksTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		NameColumn      = mysql.StringColumn("name")
		URLColumn       = mysql.StringColumn("url")
		SecretColumn    = mysql.BlobColumn("secret")
		OwnerIDColumn   = mysql.StringColumn("owner_id")
		IsActiveColumn  = mysql.BoolColumn("is_active")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
		allColumns      = mysql.ColumnList{IDColumn, NameColumn, URLColumn, SecretColumn, OwnerIDColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = mysql.ColumnList{NameColumn, URLColumn, SecretColumn, OwnerIDColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = mysql.ColumnList{IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return webhooksTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		URL:       URLColumn,
		Secret:    SecretColumn,
		OwnerID:   OwnerIDColumn,
		IsActive:  IsActiveColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
