//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var GroupMemberLogsAction = &struct {
	Added       mysql.StringExpression
	Removed     mysql.StringExpression
	RoleChanged mysql.StringExpression
}{
	Added:       mysql.NewEnumValue("added"),
	Removed:     mysql.NewEnumValue("removed"),
	RoleChanged: mysql.NewEnumValue("role_changed"),
}
