//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var MailLogsStatus = &struct {
	Unsent mysql.StringExpression
	Sent   mysql.StringExpression
	Failed mysql.StringExpression
}{
	Unsent: mysql.NewEnumValue("unsent"),
	Sent:   mysql.NewEnumValue("sent"),
	Failed: mysql.NewEnumValue("failed"),
}
