//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var SecretLogsAction = &struct {
	Created  mysql.StringExpression
	Updated  mysql.StringExpression
	Deleted  mysql.StringExpression
	Accessed mysql.StringExpression
}{
	Created:  mysql.NewEnumValue("created"),
	Updated:  mysql.NewEnumValue("updated"),
	Deleted:  mysql.NewEnumValue("deleted"),
	Accessed: mysql.NewEnumValue("accessed"),
}
