//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var UserStatusesStatus = &struct {
	Active           mysql.StringExpression
	Suspended        mysql.StringExpression
	EmailUnconfirmed mysql.StringExpression
	PendingApproval  mysql.StringExpression
}{
	Active:           mysql.NewEnumValue("active"),
	Suspended:        mysql.NewEnumValue("suspended"),
	EmailUnconfirmed: mysql.NewEnumValue("email_unconfirmed"),
	PendingApproval:  mysql.NewEnumValue("pending_approval"),
}
