//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var UserKeysAlgorithm = &struct {
	RsaOaepSha256 mysql.StringExpression
	EcdhP256      mysql.StringExpression
	EcdhP384      mysql.StringExpression
	Ed25519       mysql.StringExpression
}{
	RsaOaepSha256: mysql.NewEnumValue("RSA-OAEP-SHA256"),
	EcdhP256:      mysql.NewEnumValue("ECDH-P256"),
	EcdhP384:      mysql.NewEnumValue("ECDH-P384"),
	Ed25519:       mysql.NewEnumValue("Ed25519"),
}
