//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var UserLinksService = &struct {
	Twitter mysql.StringExpression
	Github  mysql.StringExpression
	Discord mysql.StringExpression
	Slack   mysql.StringExpression
	Google  mysql.StringExpression
}{
	Twitter: mysql.NewEnumValue("twitter"),
	Github:  mysql.NewEnumValue("github"),
	Discord: mysql.NewEnumValue("discord"),
	Slack:   mysql.NewEnumValue("slack"),
	Google:  mysql.NewEnumValue("google"),
}
