version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Bugs
    - asasalint
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - govet
    - makezero
    - nilerr
    - nilnil
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck

    # Performance
    - ineffassign
    - prealloc

    # Style
    - asciicheck
    - gocheckcompilerdirectives
    - gochecksumtype
    - misspell
    - unconvert
    - unused

    # Security
    - gosec

    # Complexity
    - funlen
    - gocognit
    - gocyclo

    # Test
    - testifylint

    # Logging
    - zerologlint

    # Proto
    - protogetter

    # Misc
    - reassign
    - spancheck

  settings:
    funlen:
      lines: 80
      statements: 60
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104  # Audit errors not checked (handled by errcheck)
    errcheck:
      check-type-assertions: true
      check-blank: true

  exclusions:
    generated: lax
    presets:
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - funlen
          - gocognit
          - gocyclo
          - errorlint
          - errcheck
      - path: gen/
        linters:
          - all

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/traPtitech/portal-oidc
  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
