services:
  oidc:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: oidc
    volumes:
      - "./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"
    healthcheck:
      test: mariadb-admin ping -h localhost -ppassword
      interval: 1s
      timeout: 10s
      retries: 60
