version: "3"

env:
  BOIL_EXT_VER: "v0.8.0"
  BOIL_VER: "v4.15.0"

tasks:
  init:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/rubenv/sql-migrate/...@latest
      - go install github.com/volatiletech/sqlboiler/v4@latest
      - go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest
  
  start:server:
    cmds:
      - go run ./cmd serve

  migrate:
    cmds:
      - sql-migrate {{ .CLI_ARGS }}
  migrate:new:
    cmds:
      - sql-migrate new _
  migrate:up:
    cmds:
      - sql-migrate up
  migrate:down:
    cmds:
      - sql-migrate down

  gen:db:
    deps:
      - gen:db:oidc
      - gen:db:portal

  gen:db:oidc:
    cmds:
      - go get -u github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}
      - sqlboiler mysql --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/main --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/test --templates {{.GOPATH}}/pkg/mod/github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}/templates/boilv4/mysql
      - go mod tidy
  gen:db:portal:
    cmds:
      - go get -u github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}
      - sqlboiler mysql --config sqlboiler.portal.toml --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/main --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/test --templates {{.GOPATH}}/pkg/mod/github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}/templates/boilv4/mysql
      - go mod tidy
