version: "3"

env:
  BOIL_EXT_VER: "v0.8.0"
  BOIL_VER: "v4.15.0"

tasks:
  start:server:
    cmds:
      - go run ./cmd serve

  migrate:
    cmds:
      - go tool sql-migrate {{ .CLI_ARGS }}
  migrate:new:
    cmds:
      - go tool sql-migrate new _
  migrate:up:
    cmds:
      - go tool sql-migrate up
  migrate:down:
    cmds:
      - go tool sql-migrate down

  gen:db:
    deps:
      - gen:db:oidc
      - gen:db:portal

  gen:db:oidc:
    cmds:
      - go get -u github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}
      - sqlboiler mysql --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/main --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/test --templates {{.GOPATH}}/pkg/mod/github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}/templates/boilv4/mysql
      - go mod tidy
  gen:db:portal:
    cmds:
      - go get -u github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}
      - sqlboiler mysql --config sqlboiler.portal.toml --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/main --templates {{.GOPATH}}/pkg/mod/github.com/volatiletech/sqlboiler/v4@{{.BOIL_VER}}/templates/test --templates {{.GOPATH}}/pkg/mod/github.com/tiendc/sqlboiler-extensions@{{.BOIL_EXT_VER}}/templates/boilv4/mysql
      - go mod tidy
