version: "3"
tasks:
  init:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/rubenv/sql-migrate/...@latest
      - go install github.com/volatiletech/sqlboiler/v4@latest
      - go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest

  migrate:
    cmds:
      - sql-migrate {{ .CLI_ARGS }}
  migrate:new:
    cmds:
      - sql-migrate new _
  migrate:up:
    cmds:
      - sql-migrate up

  gen:db:
    cmds:
      - sqlboiler mysql
