version: "3"

tasks:
  start:server:
    cmds:
      - go run ./cmd serve

  migrate:
    cmds:
      - go tool sql-migrate {{ .CLI_ARGS }}
  migrate:new:
    cmds:
      - go tool sql-migrate new _
  migrate:up:
    cmds:
      - go tool sql-migrate up
  migrate:down:
    cmds:
      - go tool sql-migrate down

  gen:
    cmds:
      - go generate ./...
