//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Clients = newClientsTable("oidc", "clients", "")

type clientsTable struct {
	mysql.Table

	// Columns
	ClientID         mysql.ColumnString
	ClientSecretHash mysql.ColumnString
	Name             mysql.ColumnString
	ClientType       mysql.ColumnString
	RedirectUris     mysql.ColumnString
	CreatedAt        mysql.ColumnTimestamp
	UpdatedAt        mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ClientsTable struct {
	clientsTable

	NEW clientsTable
}

// AS creates new ClientsTable with assigned alias
func (a ClientsTable) AS(alias string) *ClientsTable {
	return newClientsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ClientsTable with assigned schema name
func (a ClientsTable) FromSchema(schemaName string) *ClientsTable {
	return newClientsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ClientsTable with assigned table prefix
func (a ClientsTable) WithPrefix(prefix string) *ClientsTable {
	return newClientsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ClientsTable with assigned table suffix
func (a ClientsTable) WithSuffix(suffix string) *ClientsTable {
	return newClientsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newClientsTable(schemaName, tableName, alias string) *ClientsTable {
	return &ClientsTable{
		clientsTable: newClientsTableImpl(schemaName, tableName, alias),
		NEW:          newClientsTableImpl("", "new", ""),
	}
}

func newClientsTableImpl(schemaName, tableName, alias string) clientsTable {
	var (
		ClientIDColumn         = mysql.StringColumn("client_id")
		ClientSecretHashColumn = mysql.StringColumn("client_secret_hash")
		NameColumn             = mysql.StringColumn("name")
		ClientTypeColumn       = mysql.StringColumn("client_type")
		RedirectUrisColumn     = mysql.StringColumn("redirect_uris")
		CreatedAtColumn        = mysql.TimestampColumn("created_at")
		UpdatedAtColumn        = mysql.TimestampColumn("updated_at")
		allColumns             = mysql.ColumnList{ClientIDColumn, ClientSecretHashColumn, NameColumn, ClientTypeColumn, RedirectUrisColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns         = mysql.ColumnList{ClientSecretHashColumn, NameColumn, ClientTypeColumn, RedirectUrisColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns         = mysql.ColumnList{ClientIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return clientsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ClientID:         ClientIDColumn,
		ClientSecretHash: ClientSecretHashColumn,
		Name:             NameColumn,
		ClientType:       ClientTypeColumn,
		RedirectUris:     RedirectUrisColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
