//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type GroupMemberLogsAction string

const (
	GroupMemberLogsAction_Added       GroupMemberLogsAction = "added"
	GroupMemberLogsAction_Removed     GroupMemberLogsAction = "removed"
	GroupMemberLogsAction_RoleChanged GroupMemberLogsAction = "role_changed"
)

var GroupMemberLogsActionAllValues = []GroupMemberLogsAction{
	GroupMemberLogsAction_Added,
	GroupMemberLogsAction_Removed,
	GroupMemberLogsAction_RoleChanged,
}

func (e *GroupMemberLogsAction) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "added":
		*e = GroupMemberLogsAction_Added
	case "removed":
		*e = GroupMemberLogsAction_Removed
	case "role_changed":
		*e = GroupMemberLogsAction_RoleChanged
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for GroupMemberLogsAction enum")
	}

	return nil
}

func (e GroupMemberLogsAction) String() string {
	return string(e)
}
