//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type GroupPermissions struct {
	GroupID    uuid.UUID `sql:"primary_key"`
	Permission string    `sql:"primary_key"` // Permission: user:read, user:update, invitation:create, etc.
	CreatedAt  time.Time
}
