//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type GroupKeys struct {
	GroupID      uuid.UUID `sql:"primary_key"`
	UserID       uuid.UUID `sql:"primary_key"`
	KeyID        uuid.UUID `sql:"primary_key"` // UUID v4
	EncryptedKey []byte    // Group symmetric key encrypted with user public key
	CreatedAt    time.Time
}
