//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type GroupMembers struct {
	GroupID  uuid.UUID `sql:"primary_key"`
	UserID   uuid.UUID `sql:"primary_key"`
	Roles    string    // Member roles within group: ["admin", "owner", "member"]
	JoinedAt time.Time
}
