//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Invitations struct {
	ID        uuid.UUID  `sql:"primary_key"` // UUID v4
	Code      string     // Invitation code (e.g., XXXX-XXXX-XXXX)
	CreatedBy *uuid.UUID // User who created this invitation
	UsedBy    *uuid.UUID // User who used this invitation
	ExpiresAt *time.Time // Expiration time (NULL = never expires)
	UsedAt    *time.Time
	CreatedAt time.Time
}
