//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Mails struct {
	ID         uuid.UUID `sql:"primary_key"` // UUID v4
	To         *string   // Recipients (format: @trap_id;@trap_id2)
	Subject    *string
	Body       *string
	OperatorID *uuid.UUID // User who sent this mail
	CreatedAt  time.Time
}
