//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type MailLogs struct {
	ID        uuid.UUID `sql:"primary_key"` // UUID v4
	MailID    uuid.UUID
	Status    MailLogsStatus // Mail delivery status
	Error     *string
	CreatedAt time.Time
}
