//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type MailLogsStatus string

const (
	MailLogsStatus_Unsent MailLogsStatus = "unsent"
	MailLogsStatus_Sent   MailLogsStatus = "sent"
	MailLogsStatus_Failed MailLogsStatus = "failed"
)

var MailLogsStatusAllValues = []MailLogsStatus{
	MailLogsStatus_Unsent,
	MailLogsStatus_Sent,
	MailLogsStatus_Failed,
}

func (e *MailLogsStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "unsent":
		*e = MailLogsStatus_Unsent
	case "sent":
		*e = MailLogsStatus_Sent
	case "failed":
		*e = MailLogsStatus_Failed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for MailLogsStatus enum")
	}

	return nil
}

func (e MailLogsStatus) String() string {
	return string(e)
}
