//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Namecards struct {
	StudentPrefix string  `sql:"primary_key"` // Student number prefix (e.g., 15B, 24B)
	Color         *string // Hex color code
}
