//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type SecretLogsAction string

const (
	SecretLogsAction_Created  SecretLogsAction = "created"
	SecretLogsAction_Updated  SecretLogsAction = "updated"
	SecretLogsAction_Deleted  SecretLogsAction = "deleted"
	SecretLogsAction_Accessed SecretLogsAction = "accessed"
)

var SecretLogsActionAllValues = []SecretLogsAction{
	SecretLogsAction_Created,
	SecretLogsAction_Updated,
	SecretLogsAction_Deleted,
	SecretLogsAction_Accessed,
}

func (e *SecretLogsAction) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "created":
		*e = SecretLogsAction_Created
	case "updated":
		*e = SecretLogsAction_Updated
	case "deleted":
		*e = SecretLogsAction_Deleted
	case "accessed":
		*e = SecretLogsAction_Accessed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for SecretLogsAction enum")
	}

	return nil
}

func (e SecretLogsAction) String() string {
	return string(e)
}
