//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Secrets struct {
	ID             uuid.UUID `sql:"primary_key"` // UUID v4
	GroupID        uuid.UUID // Owning group
	Name           string
	EncryptedValue []byte // AES-GCM encrypted with group key
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
