//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserLinksService string

const (
	UserLinksService_Twitter UserLinksService = "twitter"
	UserLinksService_Github  UserLinksService = "github"
	UserLinksService_Discord UserLinksService = "discord"
	UserLinksService_Slack   UserLinksService = "slack"
	UserLinksService_Google  UserLinksService = "google"
)

var UserLinksServiceAllValues = []UserLinksService{
	UserLinksService_Twitter,
	UserLinksService_Github,
	UserLinksService_Discord,
	UserLinksService_Slack,
	UserLinksService_Google,
}

func (e *UserLinksService) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "twitter":
		*e = UserLinksService_Twitter
	case "github":
		*e = UserLinksService_Github
	case "discord":
		*e = UserLinksService_Discord
	case "slack":
		*e = UserLinksService_Slack
	case "google":
		*e = UserLinksService_Google
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserLinksService enum")
	}

	return nil
}

func (e UserLinksService) String() string {
	return string(e)
}
