//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserKeys struct {
	UserID              uuid.UUID         `sql:"primary_key"`
	KeyID               uuid.UUID         `sql:"primary_key"` // UUID v4
	PublicKey           []byte            // User public key (DER format)
	EncryptedPrivateKey []byte            // Private key encrypted with user password-derived key
	Algorithm           UserKeysAlgorithm // Key algorithm
	IsActive            bool
	CreatedAt           time.Time
}
