//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserStatuses struct {
	UserID    uuid.UUID          `sql:"primary_key"`
	Status    UserStatusesStatus `sql:"primary_key"` // Status type
	Detail    *string            // Additional detail/reason
	CreatedAt time.Time
}
