//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserStatusesStatus string

const (
	UserStatusesStatus_Active           UserStatusesStatus = "active"
	UserStatusesStatus_Suspended        UserStatusesStatus = "suspended"
	UserStatusesStatus_EmailUnconfirmed UserStatusesStatus = "email_unconfirmed"
	UserStatusesStatus_PendingApproval  UserStatusesStatus = "pending_approval"
)

var UserStatusesStatusAllValues = []UserStatusesStatus{
	UserStatusesStatus_Active,
	UserStatusesStatus_Suspended,
	UserStatusesStatus_EmailUnconfirmed,
	UserStatusesStatus_PendingApproval,
}

func (e *UserStatusesStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "active":
		*e = UserStatusesStatus_Active
	case "suspended":
		*e = UserStatusesStatus_Suspended
	case "email_unconfirmed":
		*e = UserStatusesStatus_EmailUnconfirmed
	case "pending_approval":
		*e = UserStatusesStatus_PendingApproval
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserStatusesStatus enum")
	}

	return nil
}

func (e UserStatusesStatus) String() string {
	return string(e)
}
