//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Users struct {
	ID            uuid.UUID `sql:"primary_key"` // UUID v4
	TrapID        string    // traP ID (unique username)
	PasswordHash  string    // PBKDF2-SHA512 hash
	Email         *[]byte   // AES-GCM encrypted email
	PersonalInfo  *[]byte   // AES-GCM encrypted JSON (name, phone, address, etc.)
	StudentNumber *string   // Student number (plaintext for lookup)
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
