//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserLinks struct {
	UserID      uuid.UUID        `sql:"primary_key"`
	Service     UserLinksService `sql:"primary_key"` // Service name
	ExternalID  *string          // External service user ID
	AccountName *string          // Display name/handle on the service
	AccessToken *[]byte          // Encrypted OAuth access token (if stored)
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
