//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserKeysAlgorithm string

const (
	UserKeysAlgorithm_RsaOaepSha256 UserKeysAlgorithm = "RSA-OAEP-SHA256"
	UserKeysAlgorithm_EcdhP256      UserKeysAlgorithm = "ECDH-P256"
	UserKeysAlgorithm_EcdhP384      UserKeysAlgorithm = "ECDH-P384"
	UserKeysAlgorithm_Ed25519       UserKeysAlgorithm = "Ed25519"
)

var UserKeysAlgorithmAllValues = []UserKeysAlgorithm{
	UserKeysAlgorithm_RsaOaepSha256,
	UserKeysAlgorithm_EcdhP256,
	UserKeysAlgorithm_EcdhP384,
	UserKeysAlgorithm_Ed25519,
}

func (e *UserKeysAlgorithm) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "RSA-OAEP-SHA256":
		*e = UserKeysAlgorithm_RsaOaepSha256
	case "ECDH-P256":
		*e = UserKeysAlgorithm_EcdhP256
	case "ECDH-P384":
		*e = UserKeysAlgorithm_EcdhP384
	case "Ed25519":
		*e = UserKeysAlgorithm_Ed25519
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserKeysAlgorithm enum")
	}

	return nil
}

func (e UserKeysAlgorithm) String() string {
	return string(e)
}
