//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type WebhookSubscribeEvents struct {
	WebhookID uuid.UUID `sql:"primary_key"`
	EventType string    `sql:"primary_key"` // Event type: user.created, group.member_added, etc.
	CreatedAt time.Time
}
