services:
  mongodb:
    image: mongo:8.3.2@sha256:8dbb3db48a72084457272d33d398ae0ef7db8e7c9e12815a295c3417c8df6d38
  httpd:
    image: ${CONFORMANCE_HTTPD_IMAGE}
    ports:
      - "8443:8443"
    depends_on:
      - server
  server:
    image: ${CONFORMANCE_SERVER_IMAGE}
    environment:
      - openid.mongodb.targetFeatureCompatibilityVersion=8.2
    command: >
      java
      -Djdk.tls.maxHandshakeMessageSize=65536
      -jar /server/fapi-test-suite.jar
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
    logging:
      driver: json-file
      options:
        max-size: "500k"
        max-file: "5"
