// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package oidc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAccessTokenStmt, err = db.PrepareContext(ctx, createAccessToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccessToken: %w", err)
	}
	if q.createAuthorizationCodeStmt, err = db.PrepareContext(ctx, createAuthorizationCode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuthorizationCode: %w", err)
	}
	if q.createClientStmt, err = db.PrepareContext(ctx, createClient); err != nil {
		return nil, fmt.Errorf("error preparing query CreateClient: %w", err)
	}
	if q.createOIDCSessionStmt, err = db.PrepareContext(ctx, createOIDCSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOIDCSession: %w", err)
	}
	if q.createRefreshTokenStmt, err = db.PrepareContext(ctx, createRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRefreshToken: %w", err)
	}
	if q.deleteAccessTokenByJTIStmt, err = db.PrepareContext(ctx, deleteAccessTokenByJTI); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccessTokenByJTI: %w", err)
	}
	if q.deleteAccessTokensByRequestIDStmt, err = db.PrepareContext(ctx, deleteAccessTokensByRequestID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccessTokensByRequestID: %w", err)
	}
	if q.deleteAllAccessTokensStmt, err = db.PrepareContext(ctx, deleteAllAccessTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllAccessTokens: %w", err)
	}
	if q.deleteAllAuthorizationCodesStmt, err = db.PrepareContext(ctx, deleteAllAuthorizationCodes); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllAuthorizationCodes: %w", err)
	}
	if q.deleteAllClientsStmt, err = db.PrepareContext(ctx, deleteAllClients); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllClients: %w", err)
	}
	if q.deleteAllOIDCSessionsStmt, err = db.PrepareContext(ctx, deleteAllOIDCSessions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllOIDCSessions: %w", err)
	}
	if q.deleteAllRefreshTokensStmt, err = db.PrepareContext(ctx, deleteAllRefreshTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllRefreshTokens: %w", err)
	}
	if q.deleteAuthorizationCodeStmt, err = db.PrepareContext(ctx, deleteAuthorizationCode); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthorizationCode: %w", err)
	}
	if q.deleteClientStmt, err = db.PrepareContext(ctx, deleteClient); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteClient: %w", err)
	}
	if q.deleteExpiredAccessTokensStmt, err = db.PrepareContext(ctx, deleteExpiredAccessTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredAccessTokens: %w", err)
	}
	if q.deleteExpiredAuthorizationCodesStmt, err = db.PrepareContext(ctx, deleteExpiredAuthorizationCodes); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredAuthorizationCodes: %w", err)
	}
	if q.deleteExpiredRefreshTokensStmt, err = db.PrepareContext(ctx, deleteExpiredRefreshTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredRefreshTokens: %w", err)
	}
	if q.deleteOIDCSessionStmt, err = db.PrepareContext(ctx, deleteOIDCSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOIDCSession: %w", err)
	}
	if q.deleteRefreshTokenByHashStmt, err = db.PrepareContext(ctx, deleteRefreshTokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRefreshTokenByHash: %w", err)
	}
	if q.deleteRefreshTokensByRequestIDStmt, err = db.PrepareContext(ctx, deleteRefreshTokensByRequestID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRefreshTokensByRequestID: %w", err)
	}
	if q.getAccessTokenByJTIStmt, err = db.PrepareContext(ctx, getAccessTokenByJTI); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccessTokenByJTI: %w", err)
	}
	if q.getAuthorizationCodeStmt, err = db.PrepareContext(ctx, getAuthorizationCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthorizationCode: %w", err)
	}
	if q.getClientStmt, err = db.PrepareContext(ctx, getClient); err != nil {
		return nil, fmt.Errorf("error preparing query GetClient: %w", err)
	}
	if q.getOIDCSessionStmt, err = db.PrepareContext(ctx, getOIDCSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetOIDCSession: %w", err)
	}
	if q.getRefreshTokenByHashStmt, err = db.PrepareContext(ctx, getRefreshTokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetRefreshTokenByHash: %w", err)
	}
	if q.listClientsStmt, err = db.PrepareContext(ctx, listClients); err != nil {
		return nil, fmt.Errorf("error preparing query ListClients: %w", err)
	}
	if q.markAuthorizationCodeUsedStmt, err = db.PrepareContext(ctx, markAuthorizationCodeUsed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkAuthorizationCodeUsed: %w", err)
	}
	if q.markRefreshTokenRotatedStmt, err = db.PrepareContext(ctx, markRefreshTokenRotated); err != nil {
		return nil, fmt.Errorf("error preparing query MarkRefreshTokenRotated: %w", err)
	}
	if q.revokeAccessTokensByRequestIDStmt, err = db.PrepareContext(ctx, revokeAccessTokensByRequestID); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeAccessTokensByRequestID: %w", err)
	}
	if q.revokeRefreshTokensByRequestIDStmt, err = db.PrepareContext(ctx, revokeRefreshTokensByRequestID); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeRefreshTokensByRequestID: %w", err)
	}
	if q.updateAuthorizationCodePKCEStmt, err = db.PrepareContext(ctx, updateAuthorizationCodePKCE); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthorizationCodePKCE: %w", err)
	}
	if q.updateClientStmt, err = db.PrepareContext(ctx, updateClient); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateClient: %w", err)
	}
	if q.updateClientSecretStmt, err = db.PrepareContext(ctx, updateClientSecret); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateClientSecret: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAccessTokenStmt != nil {
		if cerr := q.createAccessTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccessTokenStmt: %w", cerr)
		}
	}
	if q.createAuthorizationCodeStmt != nil {
		if cerr := q.createAuthorizationCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuthorizationCodeStmt: %w", cerr)
		}
	}
	if q.createClientStmt != nil {
		if cerr := q.createClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createClientStmt: %w", cerr)
		}
	}
	if q.createOIDCSessionStmt != nil {
		if cerr := q.createOIDCSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOIDCSessionStmt: %w", cerr)
		}
	}
	if q.createRefreshTokenStmt != nil {
		if cerr := q.createRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRefreshTokenStmt: %w", cerr)
		}
	}
	if q.deleteAccessTokenByJTIStmt != nil {
		if cerr := q.deleteAccessTokenByJTIStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccessTokenByJTIStmt: %w", cerr)
		}
	}
	if q.deleteAccessTokensByRequestIDStmt != nil {
		if cerr := q.deleteAccessTokensByRequestIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccessTokensByRequestIDStmt: %w", cerr)
		}
	}
	if q.deleteAllAccessTokensStmt != nil {
		if cerr := q.deleteAllAccessTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllAccessTokensStmt: %w", cerr)
		}
	}
	if q.deleteAllAuthorizationCodesStmt != nil {
		if cerr := q.deleteAllAuthorizationCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllAuthorizationCodesStmt: %w", cerr)
		}
	}
	if q.deleteAllClientsStmt != nil {
		if cerr := q.deleteAllClientsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllClientsStmt: %w", cerr)
		}
	}
	if q.deleteAllOIDCSessionsStmt != nil {
		if cerr := q.deleteAllOIDCSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllOIDCSessionsStmt: %w", cerr)
		}
	}
	if q.deleteAllRefreshTokensStmt != nil {
		if cerr := q.deleteAllRefreshTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllRefreshTokensStmt: %w", cerr)
		}
	}
	if q.deleteAuthorizationCodeStmt != nil {
		if cerr := q.deleteAuthorizationCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthorizationCodeStmt: %w", cerr)
		}
	}
	if q.deleteClientStmt != nil {
		if cerr := q.deleteClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteClientStmt: %w", cerr)
		}
	}
	if q.deleteExpiredAccessTokensStmt != nil {
		if cerr := q.deleteExpiredAccessTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredAccessTokensStmt: %w", cerr)
		}
	}
	if q.deleteExpiredAuthorizationCodesStmt != nil {
		if cerr := q.deleteExpiredAuthorizationCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredAuthorizationCodesStmt: %w", cerr)
		}
	}
	if q.deleteExpiredRefreshTokensStmt != nil {
		if cerr := q.deleteExpiredRefreshTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredRefreshTokensStmt: %w", cerr)
		}
	}
	if q.deleteOIDCSessionStmt != nil {
		if cerr := q.deleteOIDCSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOIDCSessionStmt: %w", cerr)
		}
	}
	if q.deleteRefreshTokenByHashStmt != nil {
		if cerr := q.deleteRefreshTokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRefreshTokenByHashStmt: %w", cerr)
		}
	}
	if q.deleteRefreshTokensByRequestIDStmt != nil {
		if cerr := q.deleteRefreshTokensByRequestIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRefreshTokensByRequestIDStmt: %w", cerr)
		}
	}
	if q.getAccessTokenByJTIStmt != nil {
		if cerr := q.getAccessTokenByJTIStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccessTokenByJTIStmt: %w", cerr)
		}
	}
	if q.getAuthorizationCodeStmt != nil {
		if cerr := q.getAuthorizationCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthorizationCodeStmt: %w", cerr)
		}
	}
	if q.getClientStmt != nil {
		if cerr := q.getClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientStmt: %w", cerr)
		}
	}
	if q.getOIDCSessionStmt != nil {
		if cerr := q.getOIDCSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOIDCSessionStmt: %w", cerr)
		}
	}
	if q.getRefreshTokenByHashStmt != nil {
		if cerr := q.getRefreshTokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRefreshTokenByHashStmt: %w", cerr)
		}
	}
	if q.listClientsStmt != nil {
		if cerr := q.listClientsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listClientsStmt: %w", cerr)
		}
	}
	if q.markAuthorizationCodeUsedStmt != nil {
		if cerr := q.markAuthorizationCodeUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markAuthorizationCodeUsedStmt: %w", cerr)
		}
	}
	if q.markRefreshTokenRotatedStmt != nil {
		if cerr := q.markRefreshTokenRotatedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markRefreshTokenRotatedStmt: %w", cerr)
		}
	}
	if q.revokeAccessTokensByRequestIDStmt != nil {
		if cerr := q.revokeAccessTokensByRequestIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeAccessTokensByRequestIDStmt: %w", cerr)
		}
	}
	if q.revokeRefreshTokensByRequestIDStmt != nil {
		if cerr := q.revokeRefreshTokensByRequestIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeRefreshTokensByRequestIDStmt: %w", cerr)
		}
	}
	if q.updateAuthorizationCodePKCEStmt != nil {
		if cerr := q.updateAuthorizationCodePKCEStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthorizationCodePKCEStmt: %w", cerr)
		}
	}
	if q.updateClientStmt != nil {
		if cerr := q.updateClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateClientStmt: %w", cerr)
		}
	}
	if q.updateClientSecretStmt != nil {
		if cerr := q.updateClientSecretStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateClientSecretStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	createAccessTokenStmt               *sql.Stmt
	createAuthorizationCodeStmt         *sql.Stmt
	createClientStmt                    *sql.Stmt
	createOIDCSessionStmt               *sql.Stmt
	createRefreshTokenStmt              *sql.Stmt
	deleteAccessTokenByJTIStmt          *sql.Stmt
	deleteAccessTokensByRequestIDStmt   *sql.Stmt
	deleteAllAccessTokensStmt           *sql.Stmt
	deleteAllAuthorizationCodesStmt     *sql.Stmt
	deleteAllClientsStmt                *sql.Stmt
	deleteAllOIDCSessionsStmt           *sql.Stmt
	deleteAllRefreshTokensStmt          *sql.Stmt
	deleteAuthorizationCodeStmt         *sql.Stmt
	deleteClientStmt                    *sql.Stmt
	deleteExpiredAccessTokensStmt       *sql.Stmt
	deleteExpiredAuthorizationCodesStmt *sql.Stmt
	deleteExpiredRefreshTokensStmt      *sql.Stmt
	deleteOIDCSessionStmt               *sql.Stmt
	deleteRefreshTokenByHashStmt        *sql.Stmt
	deleteRefreshTokensByRequestIDStmt  *sql.Stmt
	getAccessTokenByJTIStmt             *sql.Stmt
	getAuthorizationCodeStmt            *sql.Stmt
	getClientStmt                       *sql.Stmt
	getOIDCSessionStmt                  *sql.Stmt
	getRefreshTokenByHashStmt           *sql.Stmt
	listClientsStmt                     *sql.Stmt
	markAuthorizationCodeUsedStmt       *sql.Stmt
	markRefreshTokenRotatedStmt         *sql.Stmt
	revokeAccessTokensByRequestIDStmt   *sql.Stmt
	revokeRefreshTokensByRequestIDStmt  *sql.Stmt
	updateAuthorizationCodePKCEStmt     *sql.Stmt
	updateClientStmt                    *sql.Stmt
	updateClientSecretStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		createAccessTokenStmt:               q.createAccessTokenStmt,
		createAuthorizationCodeStmt:         q.createAuthorizationCodeStmt,
		createClientStmt:                    q.createClientStmt,
		createOIDCSessionStmt:               q.createOIDCSessionStmt,
		createRefreshTokenStmt:              q.createRefreshTokenStmt,
		deleteAccessTokenByJTIStmt:          q.deleteAccessTokenByJTIStmt,
		deleteAccessTokensByRequestIDStmt:   q.deleteAccessTokensByRequestIDStmt,
		deleteAllAccessTokensStmt:           q.deleteAllAccessTokensStmt,
		deleteAllAuthorizationCodesStmt:     q.deleteAllAuthorizationCodesStmt,
		deleteAllClientsStmt:                q.deleteAllClientsStmt,
		deleteAllOIDCSessionsStmt:           q.deleteAllOIDCSessionsStmt,
		deleteAllRefreshTokensStmt:          q.deleteAllRefreshTokensStmt,
		deleteAuthorizationCodeStmt:         q.deleteAuthorizationCodeStmt,
		deleteClientStmt:                    q.deleteClientStmt,
		deleteExpiredAccessTokensStmt:       q.deleteExpiredAccessTokensStmt,
		deleteExpiredAuthorizationCodesStmt: q.deleteExpiredAuthorizationCodesStmt,
		deleteExpiredRefreshTokensStmt:      q.deleteExpiredRefreshTokensStmt,
		deleteOIDCSessionStmt:               q.deleteOIDCSessionStmt,
		deleteRefreshTokenByHashStmt:        q.deleteRefreshTokenByHashStmt,
		deleteRefreshTokensByRequestIDStmt:  q.deleteRefreshTokensByRequestIDStmt,
		getAccessTokenByJTIStmt:             q.getAccessTokenByJTIStmt,
		getAuthorizationCodeStmt:            q.getAuthorizationCodeStmt,
		getClientStmt:                       q.getClientStmt,
		getOIDCSessionStmt:                  q.getOIDCSessionStmt,
		getRefreshTokenByHashStmt:           q.getRefreshTokenByHashStmt,
		listClientsStmt:                     q.listClientsStmt,
		markAuthorizationCodeUsedStmt:       q.markAuthorizationCodeUsedStmt,
		markRefreshTokenRotatedStmt:         q.markRefreshTokenRotatedStmt,
		revokeAccessTokensByRequestIDStmt:   q.revokeAccessTokensByRequestIDStmt,
		revokeRefreshTokensByRequestIDStmt:  q.revokeRefreshTokensByRequestIDStmt,
		updateAuthorizationCodePKCEStmt:     q.updateAuthorizationCodePKCEStmt,
		updateClientStmt:                    q.updateClientStmt,
		updateClientSecretStmt:              q.updateClientSecretStmt,
	}
}
