// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package oidc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAuthorizationCodeStmt, err = db.PrepareContext(ctx, createAuthorizationCode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuthorizationCode: %w", err)
	}
	if q.createClientStmt, err = db.PrepareContext(ctx, createClient); err != nil {
		return nil, fmt.Errorf("error preparing query CreateClient: %w", err)
	}
	if q.createOIDCSessionStmt, err = db.PrepareContext(ctx, createOIDCSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOIDCSession: %w", err)
	}
	if q.createTokenStmt, err = db.PrepareContext(ctx, createToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateToken: %w", err)
	}
	if q.deleteAllAuthorizationCodesStmt, err = db.PrepareContext(ctx, deleteAllAuthorizationCodes); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllAuthorizationCodes: %w", err)
	}
	if q.deleteAllClientsStmt, err = db.PrepareContext(ctx, deleteAllClients); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllClients: %w", err)
	}
	if q.deleteAllOIDCSessionsStmt, err = db.PrepareContext(ctx, deleteAllOIDCSessions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllOIDCSessions: %w", err)
	}
	if q.deleteAllTokensStmt, err = db.PrepareContext(ctx, deleteAllTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllTokens: %w", err)
	}
	if q.deleteAuthorizationCodeStmt, err = db.PrepareContext(ctx, deleteAuthorizationCode); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthorizationCode: %w", err)
	}
	if q.deleteClientStmt, err = db.PrepareContext(ctx, deleteClient); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteClient: %w", err)
	}
	if q.deleteExpiredAuthorizationCodesStmt, err = db.PrepareContext(ctx, deleteExpiredAuthorizationCodes); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredAuthorizationCodes: %w", err)
	}
	if q.deleteExpiredTokensStmt, err = db.PrepareContext(ctx, deleteExpiredTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredTokens: %w", err)
	}
	if q.deleteOIDCSessionStmt, err = db.PrepareContext(ctx, deleteOIDCSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOIDCSession: %w", err)
	}
	if q.deleteTokenStmt, err = db.PrepareContext(ctx, deleteToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteToken: %w", err)
	}
	if q.deleteTokenByAccessTokenStmt, err = db.PrepareContext(ctx, deleteTokenByAccessToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTokenByAccessToken: %w", err)
	}
	if q.deleteTokenByRefreshTokenStmt, err = db.PrepareContext(ctx, deleteTokenByRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTokenByRefreshToken: %w", err)
	}
	if q.deleteTokensByRequestIDStmt, err = db.PrepareContext(ctx, deleteTokensByRequestID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTokensByRequestID: %w", err)
	}
	if q.deleteTokensByUserAndClientStmt, err = db.PrepareContext(ctx, deleteTokensByUserAndClient); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTokensByUserAndClient: %w", err)
	}
	if q.getAuthorizationCodeStmt, err = db.PrepareContext(ctx, getAuthorizationCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthorizationCode: %w", err)
	}
	if q.getClientStmt, err = db.PrepareContext(ctx, getClient); err != nil {
		return nil, fmt.Errorf("error preparing query GetClient: %w", err)
	}
	if q.getOIDCSessionStmt, err = db.PrepareContext(ctx, getOIDCSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetOIDCSession: %w", err)
	}
	if q.getTokenByAccessTokenStmt, err = db.PrepareContext(ctx, getTokenByAccessToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetTokenByAccessToken: %w", err)
	}
	if q.getTokenByIDStmt, err = db.PrepareContext(ctx, getTokenByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTokenByID: %w", err)
	}
	if q.getTokenByRefreshTokenStmt, err = db.PrepareContext(ctx, getTokenByRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetTokenByRefreshToken: %w", err)
	}
	if q.listClientsStmt, err = db.PrepareContext(ctx, listClients); err != nil {
		return nil, fmt.Errorf("error preparing query ListClients: %w", err)
	}
	if q.markAuthorizationCodeUsedStmt, err = db.PrepareContext(ctx, markAuthorizationCodeUsed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkAuthorizationCodeUsed: %w", err)
	}
	if q.updateAuthorizationCodePKCEStmt, err = db.PrepareContext(ctx, updateAuthorizationCodePKCE); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthorizationCodePKCE: %w", err)
	}
	if q.updateClientStmt, err = db.PrepareContext(ctx, updateClient); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateClient: %w", err)
	}
	if q.updateClientSecretStmt, err = db.PrepareContext(ctx, updateClientSecret); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateClientSecret: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAuthorizationCodeStmt != nil {
		if cerr := q.createAuthorizationCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuthorizationCodeStmt: %w", cerr)
		}
	}
	if q.createClientStmt != nil {
		if cerr := q.createClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createClientStmt: %w", cerr)
		}
	}
	if q.createOIDCSessionStmt != nil {
		if cerr := q.createOIDCSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOIDCSessionStmt: %w", cerr)
		}
	}
	if q.createTokenStmt != nil {
		if cerr := q.createTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTokenStmt: %w", cerr)
		}
	}
	if q.deleteAllAuthorizationCodesStmt != nil {
		if cerr := q.deleteAllAuthorizationCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllAuthorizationCodesStmt: %w", cerr)
		}
	}
	if q.deleteAllClientsStmt != nil {
		if cerr := q.deleteAllClientsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllClientsStmt: %w", cerr)
		}
	}
	if q.deleteAllOIDCSessionsStmt != nil {
		if cerr := q.deleteAllOIDCSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllOIDCSessionsStmt: %w", cerr)
		}
	}
	if q.deleteAllTokensStmt != nil {
		if cerr := q.deleteAllTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllTokensStmt: %w", cerr)
		}
	}
	if q.deleteAuthorizationCodeStmt != nil {
		if cerr := q.deleteAuthorizationCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthorizationCodeStmt: %w", cerr)
		}
	}
	if q.deleteClientStmt != nil {
		if cerr := q.deleteClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteClientStmt: %w", cerr)
		}
	}
	if q.deleteExpiredAuthorizationCodesStmt != nil {
		if cerr := q.deleteExpiredAuthorizationCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredAuthorizationCodesStmt: %w", cerr)
		}
	}
	if q.deleteExpiredTokensStmt != nil {
		if cerr := q.deleteExpiredTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredTokensStmt: %w", cerr)
		}
	}
	if q.deleteOIDCSessionStmt != nil {
		if cerr := q.deleteOIDCSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOIDCSessionStmt: %w", cerr)
		}
	}
	if q.deleteTokenStmt != nil {
		if cerr := q.deleteTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTokenStmt: %w", cerr)
		}
	}
	if q.deleteTokenByAccessTokenStmt != nil {
		if cerr := q.deleteTokenByAccessTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTokenByAccessTokenStmt: %w", cerr)
		}
	}
	if q.deleteTokenByRefreshTokenStmt != nil {
		if cerr := q.deleteTokenByRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTokenByRefreshTokenStmt: %w", cerr)
		}
	}
	if q.deleteTokensByRequestIDStmt != nil {
		if cerr := q.deleteTokensByRequestIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTokensByRequestIDStmt: %w", cerr)
		}
	}
	if q.deleteTokensByUserAndClientStmt != nil {
		if cerr := q.deleteTokensByUserAndClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTokensByUserAndClientStmt: %w", cerr)
		}
	}
	if q.getAuthorizationCodeStmt != nil {
		if cerr := q.getAuthorizationCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthorizationCodeStmt: %w", cerr)
		}
	}
	if q.getClientStmt != nil {
		if cerr := q.getClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientStmt: %w", cerr)
		}
	}
	if q.getOIDCSessionStmt != nil {
		if cerr := q.getOIDCSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOIDCSessionStmt: %w", cerr)
		}
	}
	if q.getTokenByAccessTokenStmt != nil {
		if cerr := q.getTokenByAccessTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTokenByAccessTokenStmt: %w", cerr)
		}
	}
	if q.getTokenByIDStmt != nil {
		if cerr := q.getTokenByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTokenByIDStmt: %w", cerr)
		}
	}
	if q.getTokenByRefreshTokenStmt != nil {
		if cerr := q.getTokenByRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTokenByRefreshTokenStmt: %w", cerr)
		}
	}
	if q.listClientsStmt != nil {
		if cerr := q.listClientsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listClientsStmt: %w", cerr)
		}
	}
	if q.markAuthorizationCodeUsedStmt != nil {
		if cerr := q.markAuthorizationCodeUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markAuthorizationCodeUsedStmt: %w", cerr)
		}
	}
	if q.updateAuthorizationCodePKCEStmt != nil {
		if cerr := q.updateAuthorizationCodePKCEStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthorizationCodePKCEStmt: %w", cerr)
		}
	}
	if q.updateClientStmt != nil {
		if cerr := q.updateClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateClientStmt: %w", cerr)
		}
	}
	if q.updateClientSecretStmt != nil {
		if cerr := q.updateClientSecretStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateClientSecretStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	createAuthorizationCodeStmt         *sql.Stmt
	createClientStmt                    *sql.Stmt
	createOIDCSessionStmt               *sql.Stmt
	createTokenStmt                     *sql.Stmt
	deleteAllAuthorizationCodesStmt     *sql.Stmt
	deleteAllClientsStmt                *sql.Stmt
	deleteAllOIDCSessionsStmt           *sql.Stmt
	deleteAllTokensStmt                 *sql.Stmt
	deleteAuthorizationCodeStmt         *sql.Stmt
	deleteClientStmt                    *sql.Stmt
	deleteExpiredAuthorizationCodesStmt *sql.Stmt
	deleteExpiredTokensStmt             *sql.Stmt
	deleteOIDCSessionStmt               *sql.Stmt
	deleteTokenStmt                     *sql.Stmt
	deleteTokenByAccessTokenStmt        *sql.Stmt
	deleteTokenByRefreshTokenStmt       *sql.Stmt
	deleteTokensByRequestIDStmt         *sql.Stmt
	deleteTokensByUserAndClientStmt     *sql.Stmt
	getAuthorizationCodeStmt            *sql.Stmt
	getClientStmt                       *sql.Stmt
	getOIDCSessionStmt                  *sql.Stmt
	getTokenByAccessTokenStmt           *sql.Stmt
	getTokenByIDStmt                    *sql.Stmt
	getTokenByRefreshTokenStmt          *sql.Stmt
	listClientsStmt                     *sql.Stmt
	markAuthorizationCodeUsedStmt       *sql.Stmt
	updateAuthorizationCodePKCEStmt     *sql.Stmt
	updateClientStmt                    *sql.Stmt
	updateClientSecretStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		createAuthorizationCodeStmt:         q.createAuthorizationCodeStmt,
		createClientStmt:                    q.createClientStmt,
		createOIDCSessionStmt:               q.createOIDCSessionStmt,
		createTokenStmt:                     q.createTokenStmt,
		deleteAllAuthorizationCodesStmt:     q.deleteAllAuthorizationCodesStmt,
		deleteAllClientsStmt:                q.deleteAllClientsStmt,
		deleteAllOIDCSessionsStmt:           q.deleteAllOIDCSessionsStmt,
		deleteAllTokensStmt:                 q.deleteAllTokensStmt,
		deleteAuthorizationCodeStmt:         q.deleteAuthorizationCodeStmt,
		deleteClientStmt:                    q.deleteClientStmt,
		deleteExpiredAuthorizationCodesStmt: q.deleteExpiredAuthorizationCodesStmt,
		deleteExpiredTokensStmt:             q.deleteExpiredTokensStmt,
		deleteOIDCSessionStmt:               q.deleteOIDCSessionStmt,
		deleteTokenStmt:                     q.deleteTokenStmt,
		deleteTokenByAccessTokenStmt:        q.deleteTokenByAccessTokenStmt,
		deleteTokenByRefreshTokenStmt:       q.deleteTokenByRefreshTokenStmt,
		deleteTokensByRequestIDStmt:         q.deleteTokensByRequestIDStmt,
		deleteTokensByUserAndClientStmt:     q.deleteTokensByUserAndClientStmt,
		getAuthorizationCodeStmt:            q.getAuthorizationCodeStmt,
		getClientStmt:                       q.getClientStmt,
		getOIDCSessionStmt:                  q.getOIDCSessionStmt,
		getTokenByAccessTokenStmt:           q.getTokenByAccessTokenStmt,
		getTokenByIDStmt:                    q.getTokenByIDStmt,
		getTokenByRefreshTokenStmt:          q.getTokenByRefreshTokenStmt,
		listClientsStmt:                     q.listClientsStmt,
		markAuthorizationCodeUsedStmt:       q.markAuthorizationCodeUsedStmt,
		updateAuthorizationCodePKCEStmt:     q.updateAuthorizationCodePKCEStmt,
		updateClientStmt:                    q.updateClientStmt,
		updateClientSecretStmt:              q.updateClientSecretStmt,
	}
}
