// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package oidc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthorizationCode struct {
	Code                string         `json:"code"`
	ClientID            uuid.UUID      `json:"client_id"`
	UserID              uuid.UUID      `json:"user_id"`
	RedirectUri         string         `json:"redirect_uri"`
	Scopes              string         `json:"scopes"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	Nonce               sql.NullString `json:"nonce"`
	Used                bool           `json:"used"`
	ExpiresAt           time.Time      `json:"expires_at"`
	CreatedAt           time.Time      `json:"created_at"`
}

type Client struct {
	ClientID         uuid.UUID       `json:"client_id"`
	ClientSecretHash sql.NullString  `json:"client_secret_hash"`
	Name             string          `json:"name"`
	ClientType       string          `json:"client_type"`
	RedirectUris     json.RawMessage `json:"redirect_uris"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type OidcSession struct {
	AuthorizeCode string         `json:"authorize_code"`
	ClientID      uuid.UUID      `json:"client_id"`
	UserID        uuid.UUID      `json:"user_id"`
	Scopes        string         `json:"scopes"`
	Nonce         sql.NullString `json:"nonce"`
	AuthTime      time.Time      `json:"auth_time"`
	RequestedAt   time.Time      `json:"requested_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Token struct {
	ID           uuid.UUID      `json:"id"`
	RequestID    string         `json:"request_id"`
	ClientID     uuid.UUID      `json:"client_id"`
	UserID       uuid.UUID      `json:"user_id"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	Scopes       string         `json:"scopes"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type WebauthnChallenge struct {
	ID        uuid.UUID       `json:"id"`
	Challenge []byte          `json:"challenge"`
	UserID    uuid.NullUUID   `json:"user_id"`
	SessionID sql.NullString  `json:"session_id"`
	Type      string          `json:"type"`
	Data      json.RawMessage `json:"data"`
	ExpiresAt time.Time       `json:"expires_at"`
	CreatedAt time.Time       `json:"created_at"`
}

type WebauthnCredential struct {
	ID                uuid.UUID             `json:"id"`
	UserID            uuid.UUID             `json:"user_id"`
	CredentialID      []byte                `json:"credential_id"`
	PublicKey         []byte                `json:"public_key"`
	PublicKeyAlg      int32                 `json:"public_key_alg"`
	AttestationFormat sql.NullString        `json:"attestation_format"`
	Aaguid            uuid.NullUUID         `json:"aaguid"`
	SignCount         int64                 `json:"sign_count"`
	Transports        pqtype.NullRawMessage `json:"transports"`
	DeviceName        sql.NullString        `json:"device_name"`
	BackedUp          bool                  `json:"backed_up"`
	CreatedAt         time.Time             `json:"created_at"`
	LastUsedAt        sql.NullTime          `json:"last_used_at"`
}
