// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package oidc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuthorizationCode struct {
	Code                string         `json:"code"`
	ClientID            uuid.UUID      `json:"client_id"`
	UserID              uuid.UUID      `json:"user_id"`
	RedirectUri         string         `json:"redirect_uri"`
	Scopes              string         `json:"scopes"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	Nonce               sql.NullString `json:"nonce"`
	Used                bool           `json:"used"`
	ExpiresAt           time.Time      `json:"expires_at"`
	CreatedAt           time.Time      `json:"created_at"`
}

type Client struct {
	ClientID         uuid.UUID       `json:"client_id"`
	ClientSecretHash sql.NullString  `json:"client_secret_hash"`
	Name             string          `json:"name"`
	ClientType       string          `json:"client_type"`
	RedirectUris     json.RawMessage `json:"redirect_uris"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type OidcSession struct {
	AuthorizeCode string         `json:"authorize_code"`
	ClientID      uuid.UUID      `json:"client_id"`
	UserID        uuid.UUID      `json:"user_id"`
	Scopes        string         `json:"scopes"`
	Nonce         sql.NullString `json:"nonce"`
	AuthTime      time.Time      `json:"auth_time"`
	RequestedAt   time.Time      `json:"requested_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

type SigningKey struct {
	ID         uuid.UUID    `json:"id"`
	Kid        string       `json:"kid"`
	Algorithm  string       `json:"algorithm"`
	Use        string       `json:"use_"`
	Status     string       `json:"status"`
	PublicKey  string       `json:"public_key"`
	PrivateKey string       `json:"private_key"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	RotatedAt  sql.NullTime `json:"rotated_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type Token struct {
	ID           uuid.UUID      `json:"id"`
	RequestID    string         `json:"request_id"`
	ClientID     uuid.UUID      `json:"client_id"`
	UserID       uuid.UUID      `json:"user_id"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	Scopes       string         `json:"scopes"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
}
