// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package oidc

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Authorization Code queries
	CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) error
	// Client queries
	CreateClient(ctx context.Context, arg CreateClientParams) error
	// OIDC Session queries
	CreateOIDCSession(ctx context.Context, arg CreateOIDCSessionParams) error
	// Token queries
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	DeleteAllAuthorizationCodes(ctx context.Context) error
	DeleteAllClients(ctx context.Context) error
	DeleteAllOIDCSessions(ctx context.Context) error
	DeleteAllTokens(ctx context.Context) error
	DeleteAuthorizationCode(ctx context.Context, code string) error
	DeleteClient(ctx context.Context, clientID string) error
	DeleteExpiredAuthorizationCodes(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteOIDCSession(ctx context.Context, authorizeCode string) error
	DeleteToken(ctx context.Context, id string) error
	DeleteTokenByAccessToken(ctx context.Context, accessToken string) error
	DeleteTokenByRefreshToken(ctx context.Context, refreshToken sql.NullString) error
	DeleteTokensByRequestID(ctx context.Context, requestID string) error
	DeleteTokensByUserAndClient(ctx context.Context, arg DeleteTokensByUserAndClientParams) error
	GetAuthorizationCode(ctx context.Context, code string) (AuthorizationCode, error)
	GetClient(ctx context.Context, clientID string) (Client, error)
	GetOIDCSession(ctx context.Context, authorizeCode string) (OidcSession, error)
	GetTokenByAccessToken(ctx context.Context, accessToken string) (Token, error)
	GetTokenByID(ctx context.Context, id string) (Token, error)
	GetTokenByRefreshToken(ctx context.Context, refreshToken sql.NullString) (Token, error)
	ListClients(ctx context.Context) ([]Client, error)
	MarkAuthorizationCodeUsed(ctx context.Context, code string) error
	UpdateAuthorizationCodePKCE(ctx context.Context, arg UpdateAuthorizationCodePKCEParams) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) error
}

var _ Querier = (*Queries)(nil)
