//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ClientsClientType string

const (
	ClientsClientType_Public       ClientsClientType = "public"
	ClientsClientType_Confidential ClientsClientType = "confidential"
)

var ClientsClientTypeAllValues = []ClientsClientType{
	ClientsClientType_Public,
	ClientsClientType_Confidential,
}

func (e *ClientsClientType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "public":
		*e = ClientsClientType_Public
	case "confidential":
		*e = ClientsClientType_Confidential
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ClientsClientType enum")
	}

	return nil
}

func (e ClientsClientType) String() string {
	return string(e)
}
