//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Clients struct {
	ClientID         uuid.UUID `sql:"primary_key"`
	ClientSecretHash *string
	Name             string
	ClientType       ClientsClientType
	RedirectUris     string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
