// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package portal

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByStudentNumber(ctx context.Context, studentNumber sql.NullString) (GetUserByStudentNumberRow, error)
	GetUserByTrapID(ctx context.Context, trapID string) (GetUserByTrapIDRow, error)
	ListUserStatuses(ctx context.Context, userID uuid.UUID) ([]UserStatus, error)
}

var _ Querier = (*Queries)(nil)
